import base64
import os
import re
from typing import Any, Literal

import httpx
from inspect_ai.model import ChatMessage, ContentAudio, ContentReasoning, ContentText
from inspect_ai.solver import Generate, Solver, TaskState, solver
from inspect_ai.util import concurrency

from inspect_tts._tts_provider import TTSProvider, azure_openai_tts_provider

AudioFormat = Literal["wav", "mp3"]


@solver
def text_to_speech(
    provider: Literal["azure_openai"],
    model: str,
    voice: str,
    format: AudioFormat,
    audio_dir: str | None = None,
    save_dir: str | None = None,
    **tts_provider_kwargs: Any,
) -> Solver:
    """Replace the last message's text with audio generated by a text-to-speech model.

    The last message in the task state is mutated in-place (i.e. no new message is
    created).

    Args:
        provider (Literal["azure_openai"]): The TTS provider. (Currently only
            'azure_openai' is supported.)
        model (str): The model from the TTS provider to use for TTS.
        voice (str): The voice rom the TTS provider to use for TTS.
        format (AudioFormat): The format for the generated audio,
            either 'wav' or 'mp3'.
        audio_dir (str | None): Optional directory in which to search for
            existing audio files.
        save_dir (str | None): Optional directory in which to save audio files.
        **tts_provider_kwargs: Additional arguments to pass to the TTS provider.
    """

    async def solve(state: TaskState, generate: Generate) -> TaskState:
        # 1. Extract text from last message
        text = _extract_text_from_message(state.messages[-1])

        # 2. Get file name to search for and save audio
        file_name = _create_file_name(text, model, voice, format)

        # 2. Check for existing audio file and load it if it exists
        audio = None
        if audio_dir is not None:
            file_path = os.path.join(audio_dir, file_name)
            if os.path.exists(file_path):
                with open(file_path, "rb") as f:
                    audio = f.read()

        # 3. Generate audio if not already available
        if audio is None:
            # Get TTS provider
            client = httpx.AsyncClient()
            tts_provider = _get_tts_provider(provider, client)

            # Generate audio
            async with concurrency(provider, 10):
                audio = await tts_provider(
                    model, text, voice, format, **tts_provider_kwargs
                )

            # Save audio if directory is provided
            if save_dir is not None:
                _save_audio(audio, save_dir, file_name)

        # 4. Replace the last message's text with audio
        state.messages[-1].content = [
            ContentAudio(audio=_bytes_to_data_url(audio, format), format=format)
        ]

        return state

    return solve


def _get_tts_provider(provider: str, client: httpx.AsyncClient) -> TTSProvider:
    """Get the appropriate TTS provider based on the provider name."""
    providers = {
        "azure_openai": azure_openai_tts_provider(client),
    }

    if provider in providers:
        return providers[provider]
    else:
        raise ValueError(
            f"Provider {provider} is not supported for text-to-speech. "
            f"The supported providers are: {', '.join(providers.keys())}"
        )


def _extract_text_from_message(message: ChatMessage) -> str:
    """Extract text content from a message."""
    content = message.content

    if isinstance(content, str):
        return content
    elif isinstance(content, ContentText):
        return content.text
    elif isinstance(content, ContentReasoning):
        return content.reasoning
    else:
        raise ValueError(
            f"Content type {type(content)} is not supported for text-to-speech."
        )


def _save_audio(
    audio: bytes,
    directory: str,
    file_name: str,
) -> None:
    """Save audio data to a file."""
    os.makedirs(directory, exist_ok=True)
    file_path = os.path.join(directory, file_name)
    with open(file_path, "wb") as f:
        f.write(audio)


def _create_file_name(
    text: str,
    model: str,
    voice: str,
    format: AudioFormat,
    other_descriptors: str | None = None,
) -> str:
    """Create a path for the audio file based on the text and TTS model parameters."""
    components = [
        _sanitise_for_file_name(text),
        _sanitise_for_file_name(model),
        _sanitise_for_file_name(voice),
    ]

    if other_descriptors is not None:
        components.append(_sanitise_for_file_name(other_descriptors))

    return f"{'-'.join(components)}.{format}"


def _sanitise_for_file_name(text: str) -> str:
    """Sanitise text to be used in a file name."""
    # Replace spaces and hyphens with underscores
    sanitised = text.replace(" ", "_").replace("-", "_")

    # Remove problematic characters
    sanitised = re.sub(r'[\\/:*?"<>|]', "", sanitised)

    # Truncate to 50 characters
    return sanitised[:50]


def _bytes_to_data_url(audio: bytes, format: AudioFormat) -> str:
    """Convert audio bytes to a data URL."""
    base64_encoded = base64.b64encode(audio)
    base64_string = base64_encoded.decode("ascii")
    data_url = f"data:audio/{format};base64,{base64_string}"
    return data_url
