import base64
import os
import re
from typing import Any, Literal

from inspect_ai.model import ChatMessage, ContentAudio, ContentReasoning, ContentText
from inspect_ai.solver import Generate, Solver, TaskState, solver
from inspect_ai.util import concurrency

from inspect_tts._audio import AudioFormat
from inspect_tts._tts_provider import (
    TTSProvider,
    azure_openai_tts_provider,
    elevenlabs_tts_provider,
)


@solver
def text_to_speech(
    provider: Literal["azure_openai", "elevenlabs"],
    model: str,
    voice: str,
    format: AudioFormat,
    audio_dir: str | None = None,
    save_dir: str | None = None,
    **tts_provider_kwargs: Any,
) -> Solver:
    """Replace the last message's text with audio generated by a text-to-speech model.

    The last message in the task state is mutated in-place (i.e., no new message is
    created).

    Args:
        provider (Literal["azure_openai", "elevenlabs"]): The TTS provider.
        model (str): The model from the TTS provider to use for TTS.
        voice (str): The voice rom the TTS provider to use for TTS.
        format (AudioFormat): The format for the generated audio,
            either 'wav' or 'mp3'.
        audio_dir (str | None): Optional directory in which to search for
            existing audio files.
        save_dir (str | None): Optional directory in which to save audio files.
        **tts_provider_kwargs: Additional arguments to pass to the TTS provider.
    """

    async def solve(state: TaskState, generate: Generate) -> TaskState:
        # 1. Extract text from last message
        text = _extract_text_from_message(state.messages[-1])

        # 2. Get file name to search for and save audio
        file_name = _create_file_name(text, model, voice, format)

        # 3. Check for existing audio file and load it if it exists
        audio = None
        if audio_dir is not None:
            file_path = os.path.join(audio_dir, file_name)
            if os.path.exists(file_path):
                with open(file_path, "rb") as f:
                    audio = f.read()

        # 4. Generate audio if not already available
        if audio is None:
            tts_provider = _get_tts_provider(provider)

            # Generate audio
            async with concurrency(provider, 10):
                audio = await tts_provider(
                    model, text, voice, format, **tts_provider_kwargs
                )

            # Save audio if directory is provided
            if save_dir is not None:
                _save_audio(audio, save_dir, file_name)

        # 5. Replace the last message's text with audio
        base_format = _get_base_audio_format(format)
        state.messages[-1].content = [
            ContentAudio(
                audio=_bytes_to_data_url(audio, base_format), format=base_format
            )
        ]

        return state

    return solve


def _extract_text_from_message(message: ChatMessage) -> str:
    """Extract text content from a message."""
    content = message.content

    if isinstance(content, str):
        return content
    elif isinstance(content, ContentText):
        return content.text
    elif isinstance(content, ContentReasoning):
        return content.reasoning
    else:
        raise ValueError(
            f"Content type {type(content)} is not supported for text-to-speech."
        )


def _create_file_name(
    text: str,
    model: str,
    voice: str,
    format: AudioFormat,
    other_descriptors: str | None = None,
) -> str:
    """Create a path for the audio file based on the text and TTS model parameters."""
    components = [
        _sanitise_for_file_name(text),
        _sanitise_for_file_name(model),
        _sanitise_for_file_name(voice),
    ]

    if other_descriptors is not None:
        components.append(_sanitise_for_file_name(other_descriptors))

    return f"{'-'.join(components)}.{format}"


def _sanitise_for_file_name(text: str) -> str:
    """Sanitise text to be used in a file name."""
    # Replace spaces and hyphens with underscores
    sanitised = text.replace(" ", "_").replace("-", "_")

    # Remove problematic characters
    sanitised = re.sub(r'[\\/:*?"<>|]', "", sanitised)

    # Truncate to 50 characters
    return sanitised[:50]


def _get_tts_provider(provider: str) -> TTSProvider:
    """Get the appropriate TTS provider based on the provider name."""
    match provider:
        case "azure_openai":
            return azure_openai_tts_provider()
        case "elevenlabs":
            return elevenlabs_tts_provider()
        case _:
            raise ValueError(
                f"Provider {provider} is not supported for text-to-speech. "
                f"The supported providers are: azure_openai, elevenlabs."
            )


def _save_audio(
    audio: bytes,
    directory: str,
    file_name: str,
) -> None:
    """Save audio data to a file."""
    os.makedirs(directory, exist_ok=True)
    file_path = os.path.join(directory, file_name)
    with open(file_path, "wb") as f:
        f.write(audio)


def _get_base_audio_format(format: str) -> AudioFormat:
    if format.startswith("mp3"):
        return "mp3"
    elif format.startswith("wav"):
        return "wav"
    else:
        raise ValueError(
            f"Unsupported audio format: {format} for storing in Inspect message. "
            "Supported formats are 'wav' and 'mp3'."
        )


def _bytes_to_data_url(audio: bytes, format: AudioFormat) -> str:
    """Convert audio bytes to a data URL."""
    base64_encoded = base64.b64encode(audio)
    base64_string = base64_encoded.decode("ascii")
    data_url = f"data:audio/{format};base64,{base64_string}"
    return data_url
